### ISSUE TITLE
Error: Cannot find module 'web3'

### ISSUE THREAD

**Issue by i001962** [ZitRos/edu-ethereum-contract-deployment-example#1] opened 2019-05-02 19:32 UTC
Made it to step 5 - Run node deployContract.js and see the result.

That's were this error occured:

node deployContract.js
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by i001962** [comment] 2019-05-02 19:52
I ended up doing the following to get unstuck:
1 - Update package.json "web3": "^1.0.0-beta.53"
2- Removed node_modules folder 
3 npm init

**Comment by nikitaeverywhere** [comment] 2019-05-03 09:06
Hello!

That was possibly just a problem with your `npm install`.

If the issue is resolved, please close it :) Thanks!

**Closed as completed** 2019-05-03 13:43 UTC
